### ISSUE TITLE
Unable to resize windows on xmonad

### ISSUE THREAD

**Issue by Matt-Deacalion** [DevExpress/testcafe-browser-tools#209] opened 2021-01-20 13:58 UTC
Running the following test with TestCafe:

```js
test('…', async t => {
    await t.resizeWindow(200, 200);
});
```

I get this output:
```
 Warnings (1):
 --
  Was unable to resize the window due to an error.

  The
  /home/matt/.npm-packages/pnpm-global/4/node_modules/.pnpm/testcafe-browser-tools@2.0.13/node_modules/testcafe-browser-tools/bin/linux/glibc-64/resize
  process failed with the null exit code.
```

Chrome 87.0.4280.88 and xmonad 0.15.

**Comment by AlexKamaev** [comment] 2021-01-21 11:02
Hello,
I was able to reproduce the issue. However, I am not sure that my system was set up like yours and that the cause of the issue is the same. I followed this guide to install clean xmonad: [https://www.youtube.com/watch?v=3noK4GTmyMw](https://www.youtube.com/watch?v=3noK4GTmyMw)
I use the following configuration file: [http://code.haskell.org/xmonad/man/xmonad.hs](http://code.haskell.org/xmonad/man/xmonad.hs)
Do I need to install anything else? Could you please share your `xmonad.hs` configuration file?
Could you clarify how TestCafe should resize windows in the tiling window manager? Is the mode without tiles available as well? Can you resize the browser window when you run it without a browser?

**Comment by Matt-Deacalion** [comment] 2021-01-21 15:20
My xmonad configuration is the same as the default, I did try to _float_ Chrome windows by default (so they're not tiled and can be resized) with the following change in `xmonad.hs` on line `213`:

```haskell
myManageHook = composeAll
    [ className =? "Gimp"           --> doFloat
    , className =? "Google-chrome"  --> doFloat ]
```

I can resize the browser window by floating it (in xmonad: hold `Alt`, `right click` and drag the window).

Thank you for the response! My tests work fine if I run testcafe in `headless` mode, so I'm using that for now.

```bash
$ testcafe 'chrome:headless' tests/e2e
```

**Comment by Matt-Deacalion** [comment] 2021-01-21 15:25
**PS:** when you edit `~/xmonad/xmonad.hs` it needs to recompile, you can do this with `Alt + Tab + q` when using the default configuration.

**Comment by AndreyBelym** [comment] 2021-01-25 08:11
We use the `_NET_MOVERESIZE_WINDOW` message to resize windows on Linux platforms. This message is a part of the [Extended Window Manager Hints](https://en.wikipedia.org/wiki/Extended_Window_Manager_Hints) (EWMH) convention. Xmonad doesn't support EWMH out of the box and only partial EWMH support is offered by a third-party party plugin: [Xmonad.Hooks.EwmhDesktops](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Hooks-EwmhDesktops.html). The plugin doesn't support the `_NET_MOVERESIZE_WINDOW` message, but you could write a custom hook to handle it.

We state in our docs that your window manager should be ICCCM/EWMH compliant on Linux: [Resize Window](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/interact-with-the-page.html#resize-window). It seems that Xmonad is not completely EWMH-compliant, so I have to close this issue.

**Closed by AndreyBelym** 2021-01-25 08:11 UTC
Labels: STATE: Need clarification, STATE: Need response

**Comment by Matt-Deacalion** [comment] 2021-01-25 12:45
Thank you for the clarification @AndreyBelym - I got thrown off by this [Wikipedia page](https://en.wikipedia.org/wiki/Comparison_of_X_window_managers) and thought xmonad was `ICCCM / EWMH` compliant.
